stages:
  - migrar
  - deploy

aplicar_migraciones:
  stage: migrar
  image: python:3.10
  script:
    - pip install -r requirements.txt
    - python manage.py migrate --noinput

desplegar:
  stage: deploy
  needs: ["aplicar_migraciones"]
  script:
    - ./scripts/deploy.sh produccion
  only:
    - main
