stages:
  - build
  - deploy

build_image:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  script:
    - docker login -u biblio_admin -p "Registro.Biblio.2026" registry.biblioteca.local
    - docker build -t registry.biblioteca.local/biblio:$CI_COMMIT_SHORT_SHA .
    - docker push registry.biblioteca.local/biblio:$CI_COMMIT_SHORT_SHA

deploy:
  stage: deploy
  script:
    - sshpass -p "deploy2026" ssh deploy@app01 "./update.sh $CI_COMMIT_SHORT_SHA"
